### ISSUE TITLE
Dangerous mutation

### ISSUE THREAD

**Issue by Yomguithereal** [Srdjan/react-baobab-todoapp#1]
Hello @Srdjan. This is a nice TodoApp. However I find the following [lines](https://github.com/Srdjan/react-baobab-todoapp/blob/master/src/js/app.js#L20-L24) somewhat dangerous:

``` js
    var updated = this.cursors.todos.get().map(t => t = { id: t.id,
                                                          done: this.refs.toggleAll.checked,
                                                          archived: t.archived,
                                                          text: t.text
                                                        })
```

You are mutating the todos through `t = {...}`, which means you are mutating data inside the tree itself. In your case this does not provoke anything silly but this could in another app.

A boabab tree should be handled as if immutable (even if it is not actually immutable for perf and size reasons).

Why don't you use the map likewise?

``` js
    var updated = this.cursors.todos.get().map(t => {return { id: t.id,
                                                          done: this.refs.toggleAll.checked,
                                                          archived: t.archived,
                                                          text: t.text
                                                        }})
```

**Comment by srdjan** [comment]
oh, uh... that makes sense, I shouldn't be doing it that way... thanks!
